platform :ios, '6.0'
pod 'AFNetworking', '~> 1.3.2'
pod 'SVProgressHUD'
pod 'QuickDialog'
pod 'ADClusterMapView'
pod 'NullSafe'
pod 'UIKitCategoryAdditions', :git => 'https://github.com/pepibumur/UIKitCategoryAdditions.git'
pod 'RPRadarChart', :git => 'https://github.com/pepibumur/RPRadarChart.git'
inhibit_all_warnings!
